version: '3.7'

services: 
        inline_backend:
                build: Backend
                ports:
                        - '8080:8080'
                container_name: 'inline_backend'

        inline_rtc:
                build: groupcall-test
                ports:
                        - '8998:8998'
                container_name: 'inline_rtc'
                #depends_on:
                #        - 'inline_kms'

        inline_frontend:
                build: Frontend
                ports:
                        - '7070:80'
                container_name: 'inline_frontend'

